### ISSUE TITLE
How to check if the alert is showing?

### ISSUE THREAD

**Issue by anggaaryas** [RatelHub/rflutter_alert#106] opened 2021-06-03 07:00 UTC
like Dialog.isShowing();

my current solution is explicitly null the Alert before dismissing

**Comment by ibrahimdevs** [comment] 2021-08-03 15:02
Duplicate of #80 [QUESTION: Is there a way to know if an alert is showing?](https://github.com/RatelHub/rflutter_alert/issues/80)

**Closed as completed by ibrahimdevs** 2021-08-03 15:02 UTC
